const navs = ['Dashboard',
    'Add_members',
    'Manage_members',
    'Games',
    'Authorization_to_withdraw',
    'Automatic_transfer_waiting_list',
    'Error_transfer',
    'System_Setting',
    'Setup_withdrawal',
    'colors_backgrounds',
    'membership_page',
    'staff',
    'deposit_withdraw_money',
    'Wallet_Deposit',
    'Promotion',
    'Affiliate',
    'Alert',
    'Deposit_Withdraw_Transfer',
    'Summary_Report',
    'Affiliate_Report',
    'Money_transfer_report',
    'Making_of_admins',
    'Account_List',
    'Agent_system']
export default navs